services:
  odm2fhir:
    image: ghcr.io/num-codex/odm2fhir:0.5.1
    restart: "no"
    environment:
      ODM.REDCAP.API.URL: ${ODM_REDCAP_API_URL}
      ODM.REDCAP.API.TOKEN: ${ODM_REDCAP_API_TOKEN}
      #FHIR.SERVER.URL: ${FHIR_SERVER_URL:-http://fhir-gateway:8080/fhir} # Comment line for output in local file system (./out)
      FHIR.SERVER.BASICAUTH.USERNAME: ${FHIR_SERVER_BASICAUTH_USERNAME}
      FHIR.SERVER.BASICAUTH.PASSWORD: ${FHIR_SERVER_BASICAUTH_PASSWORD}
      FHIR.SERVER.OAUTH2.TOKEN.URL: ${FHIR_SERVER_OAUTH2_TOKEN_URL}
      FHIR.SERVER.OAUTH2.CLIENT.ID: ${FHIR_SERVER_OAUTH2_CLIENT_ID}
      FHIR.SERVER.OAUTH2.CLIENT.SECRET: ${FHIR_SERVER_OAUTH2_CLIENT_SECRET}
      # CRON: ${CRON:-"0 0 0 0 * *"}
    volumes:
      #- ${ODM_FILE_PATH:-./test-odm.xml}:/workspace/input/ODM.xml # Comment line for input from RedCap API
      - ${FHIR_BUNDLES_FOLDER_PATH:-./testdata}:/workspace/output # This is only used if fhir.server.url ist commented out
